version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./php/src:/var/www/html/
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: Tokped
      DB_USER: Minped
      DB_PASSWORD: semogatubesinilancarselalu
    restart: always

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: Minped
      POSTGRES_PASSWORD: semogatubesinilancarselalu
      POSTGRES_DB: Tokped
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql:ro

volumes:   
  pgdata:
