file_uploads = On
upload_max_filesize = 100M

post_max_size = 100M

; Gunakan Redis untuk session
session.save_handler = redis
session.save_path = "tcp://redis:6379"

; Optional: prefix biar rapi
redis.session.prefix = "PHPSESSID:"

; Optional: waktu hidup session (dalam detik)
session.gc_maxlifetime = 86400
